---
# Install Node.js via NodeSource repository

- name: Install Node.js dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add NodeSource GPG key
  ansible.builtin.shell: |
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | \
    gpg --dearmor --output /etc/apt/keyrings/nodesource.gpg
  args:
    creates: /etc/apt/keyrings/nodesource.gpg
  register: gpg_key_result

- name: Add NodeSource repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodejs_major_version }}.x nodistro main"
    state: present
    filename: nodesource
  register: repo_result

- name: Install Node.js and npm
  ansible.builtin.apt:
    name: nodejs
    state: latest
    update_cache: "{{ gpg_key_result.changed or repo_result.changed }}"