---
galaxy_info:
  author: EmberStack
  description: Install pipx for Python package management
  company: EmberStack
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - pipx
    - python
    - installer

dependencies: []