---
# FortiGate connection establishment
# This establishes the initial connection without redundant monitoring

- name: Establish initial FortiGate connection
  fortinet.fortios.fortios_monitor_fact:
    access_token: "{{ access_token }}"
    selector: "system_status"
  register: connection_test
  failed_when: false
  no_log: true

- name: Verify connection established
  assert:
    that:
      - connection_test is not failed
    fail_msg: "Unable to establish connection to FortiGate at {{ ansible_host }}:{{ ansible_httpapi_port }}"
    success_msg: "Connection established to FortiGate"