---
# Virtual IP (VIP) configuration tasks

# Configure VIPs
- name: "Configure VIP: {{ item.firewall_vip.name }}"
  fortinet.fortios.fortios_firewall_vip:
    state: "{{ item.state | default(fortigate_default_state) }}"
    access_token: "{{ access_token }}"
    vdom: "{{ item.vdom | default(vdom | default(fortigate_vdom)) }}"
    firewall_vip: "{{ item.firewall_vip }}"
  loop: "{{ fortigate_firewall_vips | default([]) }}"
  loop_control:
    label: "{{ item.firewall_vip.name }}"
  when: fortigate_firewall_vips is defined

# Configure VIP groups if defined
- name: "Configure VIP group: {{ item.firewall_vipgrp.name }}"
  fortinet.fortios.fortios_firewall_vipgrp:
    state: "{{ item.state | default(fortigate_default_state) }}"
    access_token: "{{ access_token }}"
    vdom: "{{ item.vdom | default(vdom | default(fortigate_vdom)) }}"
    firewall_vipgrp: "{{ item.firewall_vipgrp }}"
  loop: "{{ fortigate_firewall_vip_groups | default([]) }}"
  loop_control:
    label: "{{ item.firewall_vipgrp.name }}"
  when: fortigate_firewall_vip_groups is defined