---
# Main tasks for system updates

- name: Update apt cache
  apt:
    update_cache: yes

- name: Perform system upgrade
  apt:
    upgrade: "{{ updater_upgrade_type }}"
    autoremove: "{{ updater_cleanup }}"
    autoclean: "{{ updater_cleanup }}"

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot system
  reboot:
    reboot_timeout: "{{ updater_reboot_timeout }}"
  when:
    - updater_reboot_if_required
    - reboot_required.stat.exists